// Code generated; DO NOT EDIT.

package vanilla

import mapset "github.com/deckarep/golang-set/v2"

var CommandCameraEasing = mapset.NewThreadUnsafeSet(
	"linear",
	"spring",
	"in_quad",
	"out_quad",
	"in_out_quad",
	"in_cubic",
	"out_cubic",
	"in_out_cubic",
	"in_quart",
	"out_quart",
	"in_out_quart",
	"in_quint",
	"out_quint",
	"in_out_quint",
	"in_sine",
	"out_sine",
	"in_out_sine",
	"in_expo",
	"out_expo",
	"in_out_expo",
	"in_circ",
	"out_circ",
	"in_out_circ",
	"in_bounce",
	"out_bounce",
	"in_out_bounce",
	"in_back",
	"out_back",
	"in_out_back",
	"in_elastic",
	"out_elastic",
	"in_out_elastic",
)

var CommandDifficulty = mapset.NewThreadUnsafeSet(
	"normal",
	"peaceful",
	"easy",
	"hard",
	"p",
	"e",
	"n",
	"h",
)

var CommandDamageCause = mapset.NewThreadUnsafeSet(
	"piston",
	"lava",
	"campfire",
	"fire",
	"anvil",
	"magma",
	"soul_campfire",
	"wither",
	"falling_block",
	"fireworks",
	"thorns",
	"none",
	"sonic_boom",
	"contact",
	"override",
	"entity_attack",
	"projectile",
	"suffocation",
	"mace_smash",
	"fall",
	"starve",
	"ram_attack",
	"fire_tick",
	"stalactite",
	"drowning",
	"block_explosion",
	"entity_explosion",
	"void",
	"self_destruct",
	"magic",
	"charging",
	"stalagmite",
	"fly_into_wall",
	"lightning",
	"freezing",
	"temperature",
	"dehydration",
)

var CommandGameMode = mapset.NewThreadUnsafeSet(
	"default",
	"creative",
	"spectator",
	"survival",
	"adventure",
	"d",
	"c",
	"s",
	"a",
)

var CommandBoolGameRule = mapset.NewThreadUnsafeSet(
	"commandblockoutput",
	"dodaylightcycle",
	"doentitydrops",
	"dofiretick",
	"recipesunlock",
	"dolimitedcrafting",
	"domobloot",
	"domobspawning",
	"dotiledrops",
	"doweathercycle",
	"drowningdamage",
	"falldamage",
	"firedamage",
	"keepinventory",
	"mobgriefing",
	"pvp",
	"showcoordinates",
	"locatorbar",
	"showdaysplayed",
	"naturalregeneration",
	"tntexplodes",
	"sendcommandfeedback",
	"doinsomnia",
	"commandblocksenabled",
	"doimmediaterespawn",
	"showdeathmessages",
	"showtags",
	"freezedamage",
	"respawnblocksexplode",
	"showbordereffect",
	"showrecipemessages",
	"projectilescanbreakblocks",
	"tntexplosiondropdecay",
)

var CommandIntGameRule = mapset.NewThreadUnsafeSet(
	"maxcommandchainlength",
	"randomtickspeed",
	"functioncommandlimit",
	"spawnradius",
	"playerssleepingpercentage",
)

var CommandHudElement = mapset.NewThreadUnsafeSet(
	"hunger",
	"all",
	"paperdoll",
	"armor",
	"tooltips",
	"touch_controls",
	"crosshair",
	"hotbar",
	"health",
	"progress_bar",
	"air_bubbles",
	"horse_health",
	"status_effects",
	"item_text",
)

var CommandInputPermission = mapset.NewThreadUnsafeSet(
	"camera",
	"movement",
	"jump",
	"lateral_movement",
	"sneak",
	"dismount",
	"mount",
	"move_backward",
	"move_forward",
	"move_left",
	"move_right",
)

var CommandMobEvent = mapset.NewThreadUnsafeSet(
	"minecraft:pillager_patrols_event",
	"minecraft:wandering_trader_event",
	"minecraft:ender_dragon_event",
	"events_enabled",
)
