// Code generated; DO NOT EDIT.

package vanilla

import mapset "github.com/deckarep/golang-set/v2"

var WorldgenTemplatePoolId = mapset.NewThreadUnsafeSet(
	"minecraft:abandoned_camp/camp/bamboo_jungle",
	"minecraft:abandoned_camp/camp/birch_forest",
	"minecraft:abandoned_camp/camp/cherry_grove",
	"minecraft:abandoned_camp/camp/dappled_forest",
	"minecraft:abandoned_camp/camp/flower_forest",
	"minecraft:abandoned_camp/camp/forest",
	"minecraft:abandoned_camp/camp/meadow",
	"minecraft:abandoned_camp/camp/old_growth_birch_forest",
	"minecraft:abandoned_camp/camp/old_growth_pine_taiga",
	"minecraft:abandoned_camp/camp/old_growth_spruce_taiga",
	"minecraft:abandoned_camp/camp/pale_garden",
	"minecraft:abandoned_camp/camp/savanna",
	"minecraft:abandoned_camp/camp/snowy_taiga",
	"minecraft:abandoned_camp/camp/sparse_jungle",
	"minecraft:abandoned_camp/camp/swamp",
	"minecraft:abandoned_camp/camp/taiga",
	"minecraft:abandoned_camp/camp/windswept_forest",
	"minecraft:abandoned_camp/camp/wooded_badlands",
	"minecraft:abandoned_camp/tent/bamboo_jungle",
	"minecraft:abandoned_camp/tent/birch_forest",
	"minecraft:abandoned_camp/tent/cherry_grove",
	"minecraft:abandoned_camp/tent/dappled_forest",
	"minecraft:abandoned_camp/tent/flower_forest",
	"minecraft:abandoned_camp/tent/forest",
	"minecraft:abandoned_camp/tent/meadow",
	"minecraft:abandoned_camp/tent/old_growth_birch_forest",
	"minecraft:abandoned_camp/tent/old_growth_pine_taiga",
	"minecraft:abandoned_camp/tent/old_growth_spruce_taiga",
	"minecraft:abandoned_camp/tent/pale_garden",
	"minecraft:abandoned_camp/tent/savanna",
	"minecraft:abandoned_camp/tent/snowy_taiga",
	"minecraft:abandoned_camp/tent/sparse_jungle",
	"minecraft:abandoned_camp/tent/swamp",
	"minecraft:abandoned_camp/tent/taiga",
	"minecraft:abandoned_camp/tent/windswept_forest",
	"minecraft:abandoned_camp/tent/wooded_badlands",
	"minecraft:abandoned_camp/trees/acacia",
	"minecraft:abandoned_camp/trees/bamboo",
	"minecraft:abandoned_camp/trees/birch",
	"minecraft:abandoned_camp/trees/birch_bees",
	"minecraft:abandoned_camp/trees/cherry",
	"minecraft:abandoned_camp/trees/cherry_bees",
	"minecraft:abandoned_camp/trees/fancy_oak",
	"minecraft:abandoned_camp/trees/fancy_oak_bees",
	"minecraft:abandoned_camp/trees/jungle",
	"minecraft:abandoned_camp/trees/mega_jungle",
	"minecraft:abandoned_camp/trees/mega_pine",
	"minecraft:abandoned_camp/trees/oak",
	"minecraft:abandoned_camp/trees/orange_poplar",
	"minecraft:abandoned_camp/trees/pale_oak",
	"minecraft:abandoned_camp/trees/pine",
	"minecraft:abandoned_camp/trees/red_poplar",
	"minecraft:abandoned_camp/trees/spruce",
	"minecraft:abandoned_camp/trees/spruce_on_snow",
	"minecraft:abandoned_camp/trees/super_birch_bees",
	"minecraft:abandoned_camp/trees/thick_spruce",
	"minecraft:abandoned_camp/trees/yellow_poplar",
	"minecraft:trail_ruins/buildings",
	"minecraft:trail_ruins/buildings/grouped",
	"minecraft:trail_ruins/decor",
	"minecraft:trail_ruins/roads",
	"minecraft:trail_ruins/tower",
	"minecraft:trail_ruins/tower/additions",
	"minecraft:trail_ruins/tower/tower_top",
)
